# Site settings

title: Aubrey Taylor | Los Angeles based software developer.

email: aubz@aubz.me

description: >
    Aubrey Taylor is totally awesome!

author_description: >
    Enjoys sunsets, plays well with others.

baseurl: "" # the subpath of your site, e.g. /blog/

url: "http://aubz.me" # the base hostname & protocol for your site

twitter_username: aubricus

github_username:  aubricus

linkedin_username: aubreytaylor

# Build settings

markdown: kramdown

gems:
- jekyll-compass
