# Site settings

title: Aubrey Taylor | Los Angeles based web / software developer.

gravatar_url: http://www.gravatar.com/avatar/63b2b23cc7e374f5b6c775972cec610b?s=240

email: aubz@aubz.me

author_full_name: Aubrey Taylor

description: >
    Aubrey Taylor is an LA based web / software developer specializing in rich, interactive HTML, JS, CSS based web experiences.

author_description: >
    LA based developer, enjoys the intewebs and biking.

baseurl: "" # the subpath of your site, e.g. /blog/

url: "http://aubz.me" # the base hostname & protocol for your site

twitter_username: aubricus

github_username:  aubricus

instagram_username: aubricus

linkedin_username: aubreytaylor

# Build settings

markdown: kramdown

gems:
- jekyll-compass
